spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.100.2.12:3306/creative-life-dev?autoCommit=false&useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: Wo4heike
    hikari:
      connection-test-query: select 1
      maximum-pool-size: 20
      minimum-idle: 3
      max-lifetime: 60000
      validation-timeout: 60000

mybatis:
  mapper-locations: classpath*:mybatis/**/*Mapper.xml

wish_well_num: 10